

package com.konyaco.fluent.icons.filled

import androidx.compose.ui.graphics.vector.ImageVector
import com.konyaco.fluent.icons.Icons
import com.konyaco.fluent.icons.fluentIcon
import com.konyaco.fluent.icons.fluentPath

public val Icons.Filled.QrCode: ImageVector
    get() {
        if (_qrCode != null) {
            return _qrCode!!
        }
        _qrCode = fluentIcon(name = "Filled.QrCode") {
            fluentPath {
                moveTo(8.0f, 6.0f)
                lineTo(6.0f, 6.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(2.0f)
                lineTo(8.0f, 6.0f)
                close()
                moveTo(3.0f, 5.5f)
                arcTo(2.5f, 2.5f, 0.0f, false, true, 5.5f, 3.0f)
                horizontalLineToRelative(3.0f)
                arcTo(2.5f, 2.5f, 0.0f, false, true, 11.0f, 5.5f)
                verticalLineToRelative(3.0f)
                arcTo(2.5f, 2.5f, 0.0f, false, true, 8.5f, 11.0f)
                horizontalLineToRelative(-3.0f)
                arcTo(2.5f, 2.5f, 0.0f, false, true, 3.0f, 8.5f)
                verticalLineToRelative(-3.0f)
                close()
                moveTo(5.5f, 5.0f)
                arcToRelative(0.5f, 0.5f, 0.0f, false, false, -0.5f, 0.5f)
                verticalLineToRelative(3.0f)
                curveToRelative(0.0f, 0.28f, 0.22f, 0.5f, 0.5f, 0.5f)
                horizontalLineToRelative(3.0f)
                arcToRelative(0.5f, 0.5f, 0.0f, false, false, 0.5f, -0.5f)
                verticalLineToRelative(-3.0f)
                arcToRelative(0.5f, 0.5f, 0.0f, false, false, -0.5f, -0.5f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(6.0f, 16.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(2.0f)
                lineTo(6.0f, 18.0f)
                verticalLineToRelative(-2.0f)
                close()
                moveTo(3.0f, 15.5f)
                arcTo(2.5f, 2.5f, 0.0f, false, true, 5.5f, 13.0f)
                horizontalLineToRelative(3.0f)
                arcToRelative(2.5f, 2.5f, 0.0f, false, true, 2.5f, 2.5f)
                verticalLineToRelative(3.0f)
                arcTo(2.5f, 2.5f, 0.0f, false, true, 8.5f, 21.0f)
                horizontalLineToRelative(-3.0f)
                arcTo(2.5f, 2.5f, 0.0f, false, true, 3.0f, 18.5f)
                verticalLineToRelative(-3.0f)
                close()
                moveTo(5.5f, 15.0f)
                arcToRelative(0.5f, 0.5f, 0.0f, false, false, -0.5f, 0.5f)
                verticalLineToRelative(3.0f)
                curveToRelative(0.0f, 0.28f, 0.22f, 0.5f, 0.5f, 0.5f)
                horizontalLineToRelative(3.0f)
                arcToRelative(0.5f, 0.5f, 0.0f, false, false, 0.5f, -0.5f)
                verticalLineToRelative(-3.0f)
                arcToRelative(0.5f, 0.5f, 0.0f, false, false, -0.5f, -0.5f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(18.0f, 6.0f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(2.0f)
                lineTo(18.0f, 6.0f)
                close()
                moveTo(15.5f, 3.0f)
                arcTo(2.5f, 2.5f, 0.0f, false, false, 13.0f, 5.5f)
                verticalLineToRelative(3.0f)
                arcToRelative(2.5f, 2.5f, 0.0f, false, false, 2.5f, 2.5f)
                horizontalLineToRelative(3.0f)
                arcTo(2.5f, 2.5f, 0.0f, false, false, 21.0f, 8.5f)
                verticalLineToRelative(-3.0f)
                arcTo(2.5f, 2.5f, 0.0f, false, false, 18.5f, 3.0f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(15.0f, 5.5f)
                curveToRelative(0.0f, -0.28f, 0.22f, -0.5f, 0.5f, -0.5f)
                horizontalLineToRelative(3.0f)
                curveToRelative(0.28f, 0.0f, 0.5f, 0.22f, 0.5f, 0.5f)
                verticalLineToRelative(3.0f)
                arcToRelative(0.5f, 0.5f, 0.0f, false, true, -0.5f, 0.5f)
                horizontalLineToRelative(-3.0f)
                arcToRelative(0.5f, 0.5f, 0.0f, false, true, -0.5f, -0.5f)
                verticalLineToRelative(-3.0f)
                close()
                moveTo(13.0f, 13.0f)
                horizontalLineToRelative(2.75f)
                verticalLineToRelative(2.75f)
                lineTo(13.0f, 15.75f)
                lineTo(13.0f, 13.0f)
                close()
                moveTo(18.25f, 15.75f)
                horizontalLineToRelative(-2.5f)
                verticalLineToRelative(2.5f)
                lineTo(13.0f, 18.25f)
                lineTo(13.0f, 21.0f)
                horizontalLineToRelative(2.75f)
                verticalLineToRelative(-2.75f)
                horizontalLineToRelative(2.5f)
                lineTo(18.25f, 21.0f)
                lineTo(21.0f, 21.0f)
                verticalLineToRelative(-2.75f)
                horizontalLineToRelative(-2.75f)
                verticalLineToRelative(-2.5f)
                close()
                moveTo(18.25f, 15.75f)
                lineTo(18.25f, 13.0f)
                lineTo(21.0f, 13.0f)
                verticalLineToRelative(2.75f)
                horizontalLineToRelative(-2.75f)
                close()
            }
        }
        return _qrCode!!
    }

private var _qrCode: ImageVector? = null
